#!/usr/bin/env bash


# ignore "zsh is default" warning
export BASH_SILENCE_DEPRECATION_WARNING=1

export PATH="/Users/$USER/.local/bin:$PATH"
export PATH="/opt/homebrew/opt/node@20/bin:$PATH"

# homebrew
eval "$(/opt/homebrew/bin/brew shellenv)"
complete -C /opt/homebrew/bin/terraform terraform

# source aliases
if [ -e "$HOME"/.aliases ]; then
    # shellcheck disable=SC1091
    source "$HOME"/.aliases
fi

# shellcheck disable=SC1091
source "$HOME"/.bashrc

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$("/Users/$USER/miniforge3/bin/conda" 'shell.bash' 'hook' 2> /dev/null)"
# shellcheck disable=SC2181
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/$USER/miniforge3/etc/profile.d/conda.sh" ]; then
        # shellcheck disable=SC1091
        # shellcheck source=/dev/null
        . "/Users/$USER/miniforge3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/$USER/miniforge3/bin:$PATH"
    fi
fi
unset __conda_setup

if [ -f "/Users/$USER/miniforge3/etc/profile.d/mamba.sh" ]; then
    # shellcheck disable=SC1091
    # shellcheck source=/dev/null
    . "/Users/$USER/miniforge3/etc/profile.d/mamba.sh"
fi
# <<< conda initialize <<<

